// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NikitaBlog.Data;

#nullable disable

namespace NikitaBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302065753_InitSeedCategoryData")]
    partial class InitSeedCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NikitaBlog.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Title = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Title = "Hummor"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Title = "Science"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Title = "History"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
